<h1>NUMPY BASICS</h1>

In [1]:
my_list=[1,2,3]


In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange((5,5))   

TypeError: arange: scalar arguments expected instead of a tuple.

np.arrange only works with 1d and not 2d

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

use np.zeros to make array 2d 


In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

not range but <b>evenly spaced points</b> between 2 numbers

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b>Identity Matrix</b> is np.eye()

In [17]:
np.random.rand(5,5)

array([[0.44186663, 0.67397209, 0.31919213, 0.5094342 , 0.69330764],
       [0.61443408, 0.45207536, 0.44840593, 0.91864591, 0.03410373],
       [0.7001026 , 0.97860389, 0.42668399, 0.27920015, 0.2358247 ],
       [0.24832844, 0.60712672, 0.78685228, 0.87841167, 0.33367977],
       [0.4500231 , 0.61906861, 0.3434641 , 0.30895624, 0.55353422]])

<b>rand matrix</b> between 0 and 1

In [18]:
np.random.randn(2)

array([-0.20988802,  2.45193148])

<i>Randn</i> uses deviation from 0 and not between 0 and 1 like rand

In [23]:
np.random.randint(1,100,10)

array([80, 83, 50, 30, 37, 41, 71, 43,  1, 93])

<i>randint</i> returns random int between 2 values followed by size of array

In [24]:
int_mat=np.random.randint(1,100,10)

In [25]:
int_mat.reshape(5,2)

array([[82, 51],
       [20, 93],
       [86, 28],
       [98, 45],
       [39, 86]])

<B> RESHAPE </B> it changes shape of previously created matrix as per arg . Will throw error if cannot be filled completely

In [28]:
arr1=np.array([5,10,15,2,87,1]) 

In [29]:
arr1.max()

87

Returns max value of array

In [30]:
arr1.argmax()

4

argmax() returns position of array where max occurs (remember positions start from zero)

In [33]:
arr1.shape

(6,)

returns the shape in which arr is stored, single value shows 1d . dont use brackets with it as it is parameter and not function

In [34]:
arr1.dtype

dtype('int32')

tells the data type

<i><br><b> instead of importing np.random.randint again and again simply do below</b></i>

In [35]:
from numpy.random import randint as ri

In [37]:
ri(2,4,2)

array([2, 3])