<h1> Numpy Indexing and Selection </h1>

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Passing a number in sq brackets will return value at that index

In [6]:
arr[8]

8

arr[1:3] will return the sliced string from index 1 to 3 (not incl 3)

In [7]:
arr[1:3]

array([1, 2])

<hr>changing values of multiple elements

In [8]:
arr[0:5]=100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

<hr> giving value of slice to a arr variable: <br>


In [10]:
sliced_arr=arr[1:5]

In [13]:
sliced_arr[:]=-5

In [14]:
sliced_arr

array([-5, -5, -5, -5])

In [15]:
arr

array([100,  -5,  -5,  -5,  -5,   5,   6,   7,   8,   9,  10])

<i> As we can see from above example , if we make change to a slice of the array (even if we store it in another variable) the original will get changed too.</i> <br>
to overcome this we use <b> .Copy() </b> function <br>


In [17]:
arr=np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
copied_arr=arr[1:5].copy()

In [20]:
copied_arr[:]=-5

In [21]:
copied_arr

array([-5, -5, -5, -5])

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

we can see only copied_Arr got changed an the original remained the same.<hr>

 <b> Example in 2d</b>

In [26]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
 arr_2d[1,1]
    #selects element at index 1,1 implies position 2,2 

5

In [32]:
arr_2d[2]
#returns second array of 2d array

array([7, 8, 9])

<hr><i> we can also use slice to select some particular elements of an 2 array</i> <br> Below we will select the top right corner 4 elements:

In [33]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr_2d[:2,1:]
# meaning array till second row (as ending element is not included)
#and from 1st column (starting index is included)

array([[2, 3],
       [5, 6]])

<hr> <b>Conditions</b> on Arr and getting arr which fulfills it :

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
true_arr=arr>5
#gives boolean true and false to all arr elements 
#according to condition

In [39]:
true_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [42]:
arr[true_arr]
#returns the array elements for which condition is true

array([ 6,  7,  8,  9, 10])

In [43]:
#easier single step operation 
arr[arr>5]
#returns arr elements where value greater than 5

array([ 6,  7,  8,  9, 10])

<hr>